[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = true

# Remappings
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    "@forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15

[profile.default.metadata]
bytecode_hash = "ipfs"

# Network configurations
[rpc_endpoints]
hedera-testnet = "${HEDERA_TESTNET_RPC_URL}"
hedera-mainnet = "${HEDERA_MAINNET_RPC_URL}"

# Deployment configuration for Hedera Testnet
[profile.hedera-testnet]
gas_reports = ["*"]
gas_limit = 1000000  # Adjust based on Hedera's requirements
gas_price = 100000000  # Adjust based on Hedera's pricing model
block_gas_limit = 15000000

# Deployment configuration for Hedera Mainnet
[profile.hedera-mainnet]
gas_reports = ["*"]
gas_limit = 1000000  # Adjust based on Hedera's requirements
gas_price = 100000000  # Adjust based on Hedera's pricing model
block_gas_limit = 15000000
