[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = true

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
    "@forge-std/=lib/forge-std/src/",
    "chainlink-ccip/=lib/chainlink-ccip/chains/evm"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15

[profile.default.metadata]
bytecode_hash = "ipfs"

# Network configurations
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Deployment configuration for Sepolia
[profile.sepolia]
# Inherits all settings from default profile
# Only override Sepolia-specific settings
gas_reports = ["*"]
gas_limit = 30000000
block_gas_limit = 30000000
gas_price = 1000000000  # 1 gwei
