[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
evm_version = "paris"
via_ir = true

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
    "@forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15

[profile.default.metadata]
bytecode_hash = "ipfs"
